multipart:
  #单个文件最大
  maxFileSize:  3000MB
  #设置总上传数据总大小
  maxRequestSize: 10000MB
  uploadFolder: F:/uploads
  #1024*1024=1 048 576,5M=5 242 880
  chunkSize: 5 242 880

#thymeleaf页面模板配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html
    encoding: UTF-8
    cache: false



