multipart:
  #单个文件最大
  maxFileSize:  3000MB
  #设置总上传数据总大小
  maxRequestSize: 10000MB
  uploadFolder: /data/tmp

#thymeleaf页面模板配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html
    encoding: UTF-8
    cache: false

  # redis 缓存配置
  cache:
    redis:
      time-to-live: 60s
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 6
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 30
        min-idle: 5
        max-wait: 10000ms


