multipart:
  #单个文件最大
  max-file-size:  3000MB
  #设置总上传数据总大小
  max-request-size: 10000MB
  # 上传目录
  upload-folder: F:/uploads
  # 1024*1024=1 048 576,5M=5 242 880
  chunk-size: 5 242 880

#thymeleaf页面模板配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html
    encoding: UTF-8
    cache: false



